### ISSUE TITLE
failed to compile with kernel 3.8

### ISSUE THREAD

**Issue by tori3ama** [robopeak/rpusbdisp#2]
Kernel source is from ubuntu linux-source-3.8.0_3.8.0-23.34_all.deb, got compilation error:

$ make KERNEL_SOURCE_DIR=/usr/src/linux-source-3.8.0/ 
make -C /usr/src/linux-source-3.8.0/ KCPPFLAGS="-I/root/rpusbdisp/drivers/linux-driver/src -I/root/rpusbdisp/drivers/linux-driver/../common" M=/root/rpusbdisp/drivers/linux-driver modules
make[1]: Entering directory `/usr/src/linux-source-3.8.0'
  CC [M]  /root/rpusbdisp/drivers/linux-driver/src/main.o
  CC [M]  /root/rpusbdisp/drivers/linux-driver/src/usbhandlers.o
/root/rpusbdisp/drivers/linux-driver/src/usbhandlers.c: In function ‘rpusbdisp_usb_try_send_image’:
/root/rpusbdisp/drivers/linux-driver/src/usbhandlers.c:467:9: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t’ [-Wformat]
/root/rpusbdisp/drivers/linux-driver/src/usbhandlers.c: In function ‘_on_alloc_disp_tickets_pool’:
/root/rpusbdisp/drivers/linux-driver/src/usbhandlers.c:683:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ [-Wformat]
  CC [M]  /root/rpusbdisp/drivers/linux-driver/src/fbhandlers.o
  CC [M]  /root/rpusbdisp/drivers/linux-driver/src/touchhandlers.o
  LD [M]  /root/rpusbdisp/drivers/linux-driver/rp_usbdisplay.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/rpusbdisp/drivers/linux-driver/rp_usbdisplay.mod.o
  LD [M]  /root/rpusbdisp/drivers/linux-driver/rp_usbdisplay.ko
make[1]: Leaving directory`/usr/src/linux-source-3.8.0'

Seems it's because the removal of __devinitdata by commit torvalds/linux@63a29f744fe1c19742039ce7526663a98f172f7e in kernel.
